#!/usr/bin/env bash
set -e

# Simple script for converting danbooru-style tag prompt for SD1.5/SDXL Lora
# into natural language description for Flux.1.
#
# Usage with GNU parallel:
# 	find dir -name '*.txt' -print0 | parallel --bar -j ${NJOBS} -0 ~/vcs/scripts/llm-prompt-convert '{}' '../test/{}'

# This script requires curl, jo and a running local LLM server

infile="$1"
outfile="$2"
llm_server="${3-http://localhost:5000}/v1/chat/completions"

json_req="$(jo messages="$(jo -a "$(jo role="user" content="Convert the following danbooru-style, comma separated tags for image generation into natural-language style description, the first tag is artist name, it should be in plain text, without any formatting, and nothing else:\n""$(cat "$infile")")")")"

{ # to stderr
echo "#############"
echo "<< ${file}"
echo ": ${json_req}"
} 1>&2

output=$(curl -sS --connect-timeout 200 "${llm_server}" \
	-H "Content-Type: application/json" \
	-H "Authorization: Bearer ${AUTH_TOKEN}" \
	-d "${json_req}" \
	| jq -r ".choices[0].message.content")

echo "${output}" > "$2"

{ # to stderr
echo "------"
echo "LLM> ${output}"
} 1>&2
