#!/usr/bin/env bash

# This script requires ImageMagick

por="$1"
square="$2"
land="$3"
ignore='-'

shift 3

for i in "$@"; do
	res="$(identify -format "%w.%h" "$i")"
	width="${res%.*}"
	height="${res#*.}"

	echo ">> $i"

	if [ "$width" -lt "$height" ]; then
		[ "$por" != "$ignore" ] && mv "$i" "$por"
	elif [ "$width" -eq "$height" ]; then
		[ "$square" != "$ignore" ] && mv "$i" "$square"
	elif [ "$width" -gt "$height" ]; then
		[ "$land" != "$ignore" ] && mv "$i" "$land"
	else
		echo ">>>>>>>>> I suppose there's some kind of error here!! <<<<<<<<<<<"
	fi
done
