#!/usr/bin/env zsh

msg_echo()
{
	echo -e "\e[44m>>\e[0m \e[32m${@}\e[0m"
}

file="$1"

msg_echo "$file"
if [[ "$file" = *.png ]]; then
	if [[ "$(identify -format '%[type]' "$file")" = *Alpha ]] ; then
		optipng -v -o7 "$file"
	else
		convert -quality 100 "$file" "${file}.jpg" && \
		jpegoptim -v "${file}.jpg" && \
		rm -f "$file"
	fi
elif [[ "$file" = *.jpg ]] || [[ "$file" = *.jpeg ]]; then
	jpegoptim -v "${file}"
fi
