#!/usr/bin/env bash

set -ex

if [ $# -lt 1 ]; then
	PIXIV_ID="`xclip -selection clipboard -o`"
else
	PIXIV_ID="$1"
fi
PIXIV_ID="${PIXIV_ID##*/}"

echo "$PIXIV_ID"

if ls ~/pic/*/"$PIXIV_ID"* ; then
	echo 'exist'
else
	echo 'non'
fi
