#!/usr/bin/env bash

# This script requires ImageMagick

compare="$1"
shift 1

for i in "$@"; do
	res=`identify -format "%w.%h" "$i"`
	width="${res%.*}"
	height="${res#*.}"

	if [ "$width" "$compare" "$height" ]; then
		echo "$i"
	fi
done
