#!/usr/bin/env bash
# Uptime Recorder v0.9
# 2017/04/29
# Neo_Chen <chenkolei@gmail.com>
# Released to Public Domain

dir="${1:-/var/log}"
uptime=$(cut -d ' ' -f 1 /proc/uptime)
idletime=$(cut -d ' ' -f 2 /proc/uptime)
current="$(date +'%Y/%m/%dT%H%M%S%z')"
since="$(date -d @$(sed -n '/^btime /s///p' /proc/stat) +'%Y/%m/%dT%H%M%S%z')"
if [ -d "$dir"  ];then
	printf '%s\t%s\t%s\t%s\n' "$since" "$current" "$uptime" "$idletime" >> "$dir"/uptimerec.lst

	{
	printf '%s\t%s\t%s\t%s\n' "$since" "$current" "$uptime" "$idletime"
	cat /proc/stat
	printf '\n%%%%----%%%%\n'
	} >> "$dir"/stat.lst

else
	exit 1
fi

if [ -e "$dir"/totaluptime.rec ];then
	last=$(cat "$dir"/totaluptime.rec)
	echo "scale=10;${last}+${uptime}" | bc -l > "$dir"/totaluptime.rec
else
	echo "$uptime" > "$dir"/totaluptime.rec
fi
# vim: set tabstop=8:softtabstop=8:shiftwidth=8
