#!/usr/bin/env sh
# VCS Auto Update script -- update all repositorys under a directory
# Usage : vcs-autoupd.sh [dir]
set -e

RETURN=0

incret()
{
	RETURN=$(( $RETURN + 1))
}

if [ -n "${1}" ]; then
	cd "${1}"
fi

for dir in */ ;do
	(
	cd "${dir}"
	printf '\033[1;34m>>\033[32m%s\033[1;34m<<\033[0m\n' "${dir%/}"
	if [ -d .git/ ];then
		git pull || incret
	elif [ -d .hg/ ];then
		hg up || incret
	elif [ -d .svn/ ];then
		svn up || incret
	elif [ -d CVS/ ];then
		cvs -qz 6 up -A -Pd || incret
	elif [ -d .bzr ];then
		bzr pull || incret
	fi

	printf '\033[36m========\033[0m\n'
	)
done

[ "${RETURN}" != 0 ] && echo "Something failed..." || echo "Done!"

exit "${RETURN}"
